package com.zxxz.ssh.entity;

import java.io.Serializable;

// Generated 2017-3-25 11:17:52 by Hibernate Tools 5.2.1.Final



/**
 * Comment generated by hbm2java
 */

public class Comment implements Serializable {

	/**
	 * @author zshuaijieAKI
	 */
	private static final long serialVersionUID = 1L;
	private int comment_id;
	private int infoId;
    private String context;
	private String commTime;
	private int userId;
	private int status;
	public Comment() {
	}
	public Comment(int comment_id, int infoId, String context, String commTime, int userId,int status) {
		this.comment_id = comment_id;
		this.infoId = infoId;
		this.context = context;
		this.commTime = commTime;
		this.userId=userId;
		this.status=status;
	}
	
	public void setStatus(int status) {
		this.status = status;
	}
	public int getStatus() {
		return status;
	}
	public int getUserId() {
		return userId;
	}
	
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public int getComment_id() {
		return comment_id;
	}
	public void setComment_id(int comment_id) {
		this.comment_id = comment_id;
	}
	public int getInfoId() {
		return infoId;
	}

	public void setInfoId(int infoId) {
		this.infoId = infoId;
	}

	public String getContext() {
		return context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	public String getCommTime() {
		return commTime;
	}

	public void setCommTime(String commTime) {
		this.commTime = commTime;
	}

	

	
	

}
