package com.zxxz.ssh.entity;
// Generated 2017-3-25 11:17:52 by Hibernate Tools 5.2.1.Final


import java.io.Serializable;

/**
 * MovieComment generated by hbm2java
 */

public class MovieComment implements Serializable {

	/**
	 * @author zshuaijieAKI
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private int userid;
	private int movieid;
	private double score;
	private String context;
	private String commTime;
	
	private int status;
  
	
	public int getMovieid() {
		return movieid;
	}
	public void setMovieid(int movieid) {
		this.movieid = movieid;
	}
	public MovieComment() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
     
	public int getUserid() {
		return userid;
	}
	public void setUserid(int userid) {
		this.userid = userid;
	}
	public double getScore() {
		return score;
	}

	public void setScore(double score1) {
		this.score = score1;
	}

	public String getContext() {
		return context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	public String getCommTime() {
		return commTime;
	}

	public void setCommTime(String commTime) {
		this.commTime = commTime;
	}

	
	
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "MovieComment [id=" + id + ", userid=" + userid + ", movieid=" + movieid + ", score=" + score
				+ ", context=" + context + ", commTime=" + commTime + ", status=" + status + "]";
	}

	

}
