package com.zxxz.ssh.entity;

import java.io.Serializable;

// Generated 2017-3-25 11:17:52 by Hibernate Tools 5.2.1.Final
/**
 * News generated by hbm2java
 */

public class News implements Serializable {

	/**
	 * @author zshuaijieAKI
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private int movieId;
	private String title;
	private String context;
	private String zone;
	private String date;

	public News() {
	}

	public News(int id, int movieId, String title, String context, String zone, String date) {
		this.id = id;
		this.movieId = movieId;
		this.title = title;
		this.context = context;
		this.zone = zone;
		this.date = date;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getMovieId() {
		return movieId;
	}

	public void setMovieId(int movieId) {
		this.movieId = movieId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContext() {
		return context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	public String getZone() {
		return zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Override
	public String toString() {
		return "News [id=" + id + ", movieId=" + movieId + ", title=" + title + ", context=" + context + ", zone="
				+ zone + ", date=" + date + "]";
	}

	

}
